platform :ios, '13.0'
target 'DeepSight' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  pod 'SensingKit'
  # For the latest development version, please use:
  # pod 'SensingKit', :git => 'https://github.com/SensingKit/SensingKit-iOS.git', :branch => 'next'

  pod 'Alamofire', '~> 5.2'
  pod 'SSZipArchive'
  pod 'ZIPFoundation'
  pod 'ARVideoKit', :git => 'https://github.com/mad1n0/ARVideoKit', :branch => 'swift_5'
  pod 'SwiftyJSON'
  pod 'Zip'
  pod 'ResearchKit', :git => 'https://github.com/ResearchKit/ResearchKit.git', :branch => 'master'
  pod 'TrueScale'

end
